# remote_theme: carlosperate/jekyll-theme-rtd
# remote_theme: rundocs/jekyll-rtd-theme
remote_theme: zhangfuwen/hichambentaieb.github.io
#remote_theme: chrisbobbe/jekyll-theme-prologue
#remote_theme: pmarsceill/just-the-docs


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "/GitNote" # the subpath of your site, e.g. /blog
# url: "http://zhangfuwen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  - scope:
      path: "attachments"
    values:
      attachment: true

gittalk:
  # Note: A GitHub Application is needed for authorization, if you don't have one, going to https://github.com/settings/applications/new register a new one.
  # You must specify the website domain url in the Authorization callback URL field.
  clientID: 454d90002189d195aeae  # GitHub Application Client ID
  clientSecret: 434eb13aa18d58a1e14f5acd1dc5eded4f50d223  # GitHub Application Client Secret,
  repository: GitNote  # Storage gittalk's repository
  owner: zhangfuwen  # GitHub repo owner,
  admin: zhangfuwen  # GitHub repo owner and collaborators, only these guys can initialize github issues eg. 'colynn,daattali'


plugins:
  - jemoji
  - jekyll-asciidoc